### ISSUE TITLE
有关获得IMCS-NORM_test.json的问题

### ISSUE THREAD

**Issue by Yui-Aragakki** [winninghealth/ccl2021-subtask2#1]
请问该如何获取IMCS-NORM_test.json这个文件呢？我将下载好的IMCS-NER_test.json放在imcs_results路径下运行python entity_normalization.py但是报错

**Comment by Yui-Aragakki** [comment]
以下提及存在歧义：
呼噜呼噜 ['痰鸣音', '粗糙呼吸音']
咕噜咕噜 ['肠鸣音', '痰鸣音']
喘 ['喘息', '哮喘', '咳喘']
呼噜呼噜的声音 ['粗糙呼吸音', '痰鸣音']
痛 ['咽喉不适', '腹痛', '头痛']
----------------------
Traceback (most recent call last):
  File "entity_normalization.py", line 161, in <module>
    test_span_info = bio2span(test_data, test_result)
  File "entity_normalization.py", line 54, in bio2span
    bio_label = test_ner_file[eid][sentence_id].split()
KeyError: '1'
